require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Project4D' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'


  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  target 'Project4DTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Project4D-tvOS' do
  # Pods for Project4D-tvOS

  target 'Project4D-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
